### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by JefferyMeverden** [schiltz3/The-DMs-Toolkit#34]
Parent #46
**Tasks**
- [ ] Create Logo Button for Home Page.
- [ ] Create Button for Character Generator.
- [ ] Create Button for Encounter Generator.
- [ ] Create Button for Loot Generator.
